#!/usr/bin/env bash
# installs nginx on server

apt-get -y update
apt-get -y install nginx

service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" >> /var/www/html/index.html
service nginx restart
