#!/usr/bin/env bash
# configures Nginx server so that /redirect_me is redirecting to another page
# The redirection must be a “301 Moved Permanently”

apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html

if ! grep -q "location /redirect_me" /etc/nginx/sites-available/default; then
    sed -i '/listen \[::\]:80 default_server;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;\n\t}' /etc/nginx/sites-available/default
fi
service nginx restart
