#!/usr/bin/env bash
# have a custom 404 page
# Install nginx if it is not already installed
if ! command -v nginx &> /dev/null
then
    apt-get update
    apt-get install -y nginx
fi
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html

CONFIG_FILE="/etc/nginx/sites-available/default"
if ! grep -q "error_page 404 /404.html;" $CONFIG_FILE; then
    sed -i 's/listen \[::\]:80 default_server;/&\n\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\tinternal;\n\t}/' $CONFIG_FILE
fi
service nginx restart
