#!/usr/bin/env bash
# configure web-02 to be identical to web-01
# Install nginx if it is not already installed

apt-get update
apt-get install -y nginx

# allow incoming HTTP traffic on port 80
ufw allow 'Nginx HTTP'
echo "Hello World!" >> /var/www/html/index.html
if ! grep -q "location /redirect_me" /etc/nginx/sites-available/default; then
    sed -i '/listen \[::\]:80 default_server;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=9a6U-BF-T6g;\n\t}' /etc/nginx/sites-available/default
fi

# Create the custom 404 error page
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html

CONFIG_FILE="/etc/nginx/sites-available/default"
if ! grep -q "error_page 404 /404.html;" $CONFIG_FILE; then
    sed -i 's/listen \[::\]:80 default_server;/&\n\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\tinternal;\n\t}/' $CONFIG_FILE
fi

# Add custom HTTP response header
if ! grep -q "add_header X-Served-By \$HOSTNAME;" /etc/nginx/sites-available/default; then
    sed -i "/^server {/a \\\tadd_header X-Served-By \$HOSTNAME;" /etc/nginx/sites-available/default

fi
sudo service nginx restart
