#!/usr/bin/env bash
# Configure HAproxy load balancer

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get update -y
sudo apt-get install -y haproxy=2.8.\*

echo "frontend balancer
	bind *:80
	default_backend servers
backend servers
	balance roundrobin
	server web-01 100.25.102.62:80
	server web-02 52.87.24.245:80
" > /etc/haproxy/haproxy.cfg

service haproxy restart
