#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get update -y
sudo apt-get install -y haproxy=2.8.\*


if ! grep -q "listen http-in" /etc/haproxy/haproxy.cfg; then
    echo "listen http-in" >> /etc/haproxy/haproxy.cfg
fi
if ! grep -q "bind \*:80" /etc/haproxy/haproxy.cfg; then
    echo "bind *:80" >> /etc/haproxy/haproxy.cfg
fi
if ! grep -q "mode http" /etc/haproxy/haproxy.cfg; then
    echo "mode http" >> /etc/haproxy/haproxy.cfg
fi

if ! grep -q "balance roundrobin" /etc/haproxy/haproxy.cfg; then
    echo "balance roundrobin" >> /etc/haproxy/haproxy.cfg
fi
if ! grep -q "server 284492-web-01 100.25.102.62:80 check" /etc/haproxy/haproxy.cfg; then
    echo "server 284492-web-01 100.25.102.62:80 check" >> /etc/haproxy/haproxy.cfg
fi
if ! grep -q "server 284492-web-02 52.87.24.245:80 check" /etc/haproxy/haproxy.cfg; then
    echo "server 284492-web-02 52.87.24.245 check" >> /etc/haproxy/haproxy.cfg
fi
        

# Enable HAproxy init script
if ! grep -q "ENABLED=1" /etc/default/haproxy; then
    sudo sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
fi
# Restart HAproxy
sudo service haproxy restart
