#!/usr/bin/env bash
# A script that displays Best School 9 times and Hi on the 10th using
#a while loop 

i=0
while [ $i -lt 10 ]
do
	echo "Best School"
    if [ $i -eq 9 ]
        then
            echo "Hi"
    fi
    	((i = i + 1))
done
